FROM amd64/node:18-alpine AS builder

WORKDIR /app

COPY serverless.yml ./
COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 3001
EXPOSE 3002

CMD ["yarn", "run", "serverless", "offline", "start",  "--host", "0.0.0.0"]
