@local_base_url=http://localhost:3001
@dev_aws_url=""

########### LOCAL ###########

### Healthcheck
GET  {{local_base_url}}/health

### GraphQL query request
POST {{local_base_url}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL

<@ ./graphql.examples/users.query.graphql

########### SERVERLESS OFFLINE ###########

### Healthcheck
GET {{local_base_url}}/dev/health

### GraphQL query request
POST http://localhost:3002/dev/graphql
Content-Type: application/json
X-Request-Type: GraphQL

<@ ./graphql.examples/users.query.graphql

########### AWS ###########

GET {{dev_aws_url}}/health
Content-Type: application/json

### GraphQL query request
POST {{dev_aws_url}}/graphql
Content-Type: application/json
X-Request-Type: GraphQL

<@ ./graphql.examples/users.query.graphql
