service: Production-Ready-Serverless-NestJS
frameworkVersion: '>=3'

plugins:
  - serverless-plugin-typescript
  - serverless-ssm-fetch
  - serverless-offline

package:
  individually: true
  patterns:
    - "**/*.gql"
    - '!dist/**'

custom:
  serverlessSsmFetch:
    DATABASE_URL: '/dev/database/url~true'
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 15
  region: us-east-1
  logRetentionInDays: 14

functions:
  main:
    handler: src/lambda.handler
    environment:
      NODE_ENV: production
      # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    package:
      # see https://github.com/serverless/serverless-plugin-typescript/issues/170#issuecomment-1132731263
      patterns:
        - '!node_modules/.prisma/client/libquery_engine-*'
        - 'node_modules/.prisma/client/libquery_engine-rhel-*'
        - '!node_modules/prisma/libquery_engine-*'
        - '!node_modules/@prisma/engines/**'
